//card.js
"use client"

import styles from "./page.module.css";

export const cards = [
  {
    id: "blue",
    title: "Kavi Subash - Dakhineshwar",
    className: styles.blueline,
    buttons: [
      <button key="KKVS">Kavi Subhash (New Garia)</button>,
      <button key="KSKD">Shahid Khudiram</button>,
      <button key="KKNZ">Kavi Nazrul</button>,
      <button key="KGTN">Gitanjali</button>,
      <button key="KMSN">Masterda Suryasen</button>,
      <button key="KNTJ">Netaji</button>,
      <button key="KMUK">Mahanayak Uttam Kumar (Tollygunge)</button>,
      <button key="KRSB">Rabindra Sarobar</button>,
      <button key="KKHG">Kalighat</button>,
      <button key="KJPK">Jatin Das Park</button>,
      <button key="KNBN">Netaji Bhavan</button>,
      <button key="KRSD">Rabindra Sadan</button>,
      <button key="KMDI">Maidan</button>,
      <button key="KPSK_blue">Park Street</button>,
      <button key="KESP_blue">Esplanade</button>,
      <button key="KCWC">Chandni Chowk</button>,
      <button key="KCEN">Central</button>,
      <button key="KMHR">M.G. Road</button>,
      <button key="KGPK">Girish Park</button>,
      <button key="KSHO">Shobhabazar Sutanuti</button>,
      <button key="KSHY">Shyambazar</button>,
      <button key="KBEL">Belgachia</button>,
      <button key="KDMI">Dum Dum</button>,
      <button key="KBAR_blue">Noapara</button>,
      <button key="KNAP_blue">Baranagar</button>,
      <button key="KDSW">Dakhineshwar</button>,
    ],
  },
  {
    id: "purple",
    title: "Joka - Esplanade",
    className: styles.purpleline,
    buttons: [
      <button key="KJKA">Joka</button>,
      <button key="KTKP">Thakurpukur</button>,
      <button key="KSKB">Sakher Bazar</button>,
      <button key="KBCR">Behala Chowrasta</button>,
      <button key="KBBR">Behala Bazar</button>,
      <button key="KTRT">Taratala</button>,
      <button key="KMJH">Majherhat</button>,
      <button key="KMMP">Mominpur</button>,
      <button key="KDDP">Khiddirpur</button>,
      <button key="KVCT">Victoria</button>,
      <button key="KPSK_purple">Park Street</button>,
      <button key="KESP_purple">Esplanade</button>,
    ],
  },
  {
    id: "yellow",
    title: "Barasat - Noapara",
    className: styles.yellowline,
    buttons: [
      <button key="btn1_yellow">Barasat</button>,
      <button key="btn2_yellow">Hridaypur</button>,
      <button key="btn3_yellow">Behala Chowrasta</button>,
      <button key="btn4_yellow">Madhyamgram</button>,
      <button key="btn5_yellow">New Barrackpur</button>,
      <button key="btn6_yellow">Michael Nagar</button>,
      <button key="btn7_yellow">Birati</button>,
      <button key="KJHD">Jai Hind (NSCBI Airport)</button>,
      <button key="KJRO">Jessore Road</button>,
      <button key="KDCM">Dumdum Cantonment</button>,
      <button key="KNAP_yellow">Noapara</button>,
    ],
  },
  {
    id: "pink",
    title: "Barrackpore - Baranagar",
    className: styles.pinkline,
    buttons: [
      <button key="btn1_pink">Mangal Pandey (Barrackpore)</button>,
      <button key="btn2_pink">Anukul Thakur (Talpukur)</button>,
      <button key="btn3_pink">Shah Nawaz Khan (Titagarh)</button>,
      <button key="btn4_pink">Dr. Rajendra Prasad (Tata Gate)</button>,
      <button key="btn5_pink">Rishi Bankim (Khardah)</button>,
      <button key="btn6_pink">Subash Nagar</button>,
      <button key="btn7_pink">Sarat Chandra (Panihati)</button>,
      <button key="btn8_pink">Gandhi Ashram (Sodepur)</button>,
      <button key="btn9_pink">Acharya Prafulla Chandra (Agarpara)</button>,
      <button key="btn10_pink">Krishna Kali (Kamarhati)</button>,
      <button key="KBAR_pink">Baranagar</button>,
    ],
  },
  {
    id: "orange",
    title: "Kavi Subash - Jai Hind",
    className: styles.orangeline,
    buttons: [
      <button key="KKSO">Kavi Subhash (New Garia)</button>,
      <button key="KSJR">Satyajit Ray</button>,
      <button key="KJNN">Jyotirindra Nandi (Mukund Pur)</button>,
      <button key="KKSK">Kavi Sukanta (Kalika Pur)</button>,
      <button key="KHMD">Hemanta Mukhopadhyay (Ruby Hospital)</button>,
      <button key="KVIB">VIP Bazar</button>,
      <button key="KRWG">Ritwik Ghatak (Bantala Road)</button>,
      <button key="KBST">Barun Sengupta (Science City)</button>,
      <button key="KBGA">Beleghata</button>,
      <button key="KGKG">Gour Kishore Ghosh (Chingrighata)</button>,
      <button key="KNLN">Nalban</button>,
      <button key="KITC">IT Cetre</button>,
      <button key="KNBG">Nabadiganta</button>,
      <button key="KNLT">Nazrul Tirtha</button>,
      <button key="KPSB">Swapnabhor</button>,
      <button key="KBCC">Biswa Bangla Convention Centre</button>,
      <button key="KSST">Shiksha Tirtha</button>,
      <button key="KMWM">Mother's Wax Musuem</button>,
      <button key="KECP">Eco Park</button>,
      <button key="KMDP">Mangaldeep</button>,
      <button key="KCCT">City Centre-2</button>,
      <button key="KCNP">Chinar Park (Rajarhat Road)</button>,
      <button key="KVIR">VIP Road</button>,
    ],
  },
  {
    id: "green",
    title: "Teghoria - Howrah Maidan",
    className: styles.greenline,
    buttons: [
      <button key="btn1_green">Teghoria (Haldiram)</button>,
      <button key="btn2_green">Raghunathpur</button>,
      <button key="btn3_green">Baguihati</button>,
      <button key="btn4_green">Dum Dum Park</button>,
      <button key="btn5_green">Keshtopur</button>,
      <button key="SVSA">Salt Lake Sector-V</button>,
      <button key="KESA">Karunamoyee</button>,
      <button key="CPSA">Central Park</button>,
      <button key="CCSC">City Centre</button>,
      <button key="BCSD">Bengal Chemical</button>,
      <button key="SSSA">Salt Lake Stadium</button>,
      <button key="PBGB">Phool Bagan</button>,
      <button key="SDHM">Sealdah</button>,
      <button key="KESP_green">Esplanade</button>,
      <button key="MKNA">New Mahakaran</button>,
      <button key="HWHM">Howrah</button>,
      <button key="HWMN">Howrah Maidan</button>,
    ],
  },
];

// Utility function to extract button labels
export const getAllButtonLabels = () => {
  return cards.flatMap((card) => 
    card.buttons.map((button) => ({
      name: button.props.children, 
      color: card.id,
    }))
  );
};
